name: 'Azure Container Apps Create Revision'
description: 'Create a new revision of an Azure Container App'
inputs:
  containerAppName:
    description: 'The name of the Container App to create a revision for'
    required: true
  envVarsSelector:
    description: 'A comma separated list of environment variables to include in the deployment of the new revision. Use the format Env:VariableName to include an environment variable. Use the wildcard character (*) to match environment variables that start with a specific string. For example, Env:Api_* will match all environment variables that start with Api_'
    required: false
  envVarKeyTransform:
    description: 'Define a transformation to apply to the environment variable keys. Use the format "search=>replace" to replace all instances of search with replace in the environment variable keys. For example, _=>__ will replace all underscores with double underscores in the environment variable keys'
    required: false
  imageToDeploy:
    description: 'The full image name to deploy, including the registry and tag'
    required: true
  resourceGroup:
    description: 'The name of the resource group that contains the container app'
    required: true
    
runs:
  using: composite
  steps:
    - name: Deploy revision
      shell: pwsh
      run: |
        ${{ github.action_path }}/deploy-container-app.ps1 -Name '${{ inputs.containerAppName }}' -Image '${{ inputs.imageToDeploy }}' -ResourceGroup '${{ inputs.resourceGroup }}' -EnvVarsSelector '${{ inputs.envVarsSelector }}' -EnvVarKeyTransformString '${{ inputs.envVarKeyTransform }}' -InfA Continue
