name: Github Context
description: Log context of parent action

runs:
  using: composite
  steps:
    - name: Log github context
      run: |
        echo '## Context' >> $GITHUB_STEP_SUMMARY
        echo '### Base branch' >> $GITHUB_STEP_SUMMARY
        echo '`${{ github.event.ref }}`' >> $GITHUB_STEP_SUMMARY
        echo '### Inputs' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo $INPUTS_AS_JSON >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
      shell: bash
      env:
        INPUTS_AS_JSON: ${{ toJSON(github.event.inputs) }}