name: 'Azure SQL Deploy'
description: 'Deploy a SQL script to Azure SQL database'
inputs:
  database-name:
    description: 'Name of the Azure SQL database'
    required: true
  server-name:
    description: 'Name of the Azure SQL Server, like MyCompanyServer, or the full instance name like tcp:MyCompanyServer.database.windows.net,1433'
    required: true
  sql-file:
    description: 'Path to SQL script file to deploy'
    required: true

runs:
  using: composite
  steps:
    - name: Install dependent powershell modules
      uses: potatoqualitee/psmodulecache@ee5e9494714abf56f6efbfa51527b2aec5c761b8 # <- v6.2.1
      with:
        modules-to-cache: SqlServer:22.4.5.1
    - name: Execute SQL
      shell: pwsh
      run: |
        ${{ github.action_path }}/deploy-db.ps1 -Path '${{ inputs.sql-file }}' -SqlServerName '${{ inputs.server-name }}' -DatabaseName '${{ inputs.database-name }}' -InfA Continue
