name: Export conventions
description: Export exiting product infrastructure settings to environment variables
inputs:
  environment-name:
    description: Name of the AIG environment
    required: true

runs:
  using: composite
  steps:
    - name: Collect variables as json
      shell: pwsh
      run: ./tools/infrastructure/get-infrastructure-info.ps1 -EnvironmentName ${{ inputs.environment-name }} >> ${{ github.action_path }}/vars.json
    - name: Convert json to environment vars
      uses: antifree/json-to-variables@8de3c6b94715a24fe65f29640b4e292a4add22a3 # <- v1.2.0
      with:
        filename: ${{ github.action_path }}/vars.json
        prefix: Infra