name: __Infrastructure Deployment

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string    
      subscription-id:
        required: false
        type: string
    
jobs:
  run:
    concurrency: infra_deploy_${{ inputs.environment-name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    steps:
      - uses: actions/checkout@master
          
      - name: Set powershell module list
        shell: pwsh
        run: |
          $list = ./tools/infrastructure/provision-azure-resources.ps1 -ListModuleRequirementsOnly
          "PS_MODULE_LIST=$list" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      # note: separating the install of the pwsh modules from the main provisioning step:
      # 1. to increase the chance that the azure access token will not expire during provisioning work
      # 2. to reduce script time by caching installation
      - name: 'Install dependent powershell modules'
        uses: potatoqualitee/psmodulecache@b3b931ae410fa0639756c2dc81d3da545d12a0a0 # <- v6.0
        with:
          modules-to-cache: ${{ env.PS_MODULE_LIST }}
          
      - name: Azure login
        uses: ./.github/actions/azure-login
        with:
          enable-AzPSSession: true
          github-environment: ${{ inputs.environment-name }}
          subscription-id: ${{ inputs.subscription-id }}
          
      - name: 'Provision infrastructure'
        shell: pwsh
        run: ./tools/infrastructure/provision-azure-resources.ps1 -EnvironmentName ${{ inputs.environment-name }} -SkipInstallModules -SkipIncludeCurrentIPAddressInSQLFirewall -InfA Continue
