name: Infrastructure Deploy Production Release

on:
  release:
    types: [released]

jobs:
  
  globalvars:
    if:  ${{ startsWith(github.event.release.tag_name, 'infra-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # need to checkout so that custom action is available!
      - uses: ./.github/actions/set-global-build-vars
        id: vars
    outputs:
      buildType: ${{ steps.vars.outputs.buildType }}
      buildFullVersion: ${{ steps.vars.outputs.buildFullVersion }}
  
  demo:
    needs: globalvars
#    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: demo
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  demo-na:
    needs: globalvars
#    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: demo-na
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  demo-emea:
    needs: globalvars
#    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: demo-emea
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  demo-apac:
    needs: globalvars
#    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: demo-apac
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  staging:
    needs: globalvars
    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: staging
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  prod-na:
    needs: [globalvars, staging]
    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: prod-na
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  prod-emea:
    needs: [globalvars, staging]
    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: prod-emea
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write
  
  prod-apac:
    needs: [globalvars, staging]
    if:  ${{ needs.globalvars.outputs.buildType == 'release' }}
    uses: ./.github/workflows/__infra-deploy.yml
    with:
      environment-name: prod-apac
      build-version: ${{ needs.globalvars.outputs.buildFullVersion }}
    permissions:
      actions: read
      contents: read
      id-token: write