name: Infrastructure Remove AKS Pod-identity

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - demo
          - staging
          - prod-na
          - prod-emea
          - prod-apac

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  run-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow context
        run: |
          echo '## Context' >> $GITHUB_STEP_SUMMARY
          echo '### Base branch' >> $GITHUB_STEP_SUMMARY
          echo '`${{ github.event.ref }}`' >> $GITHUB_STEP_SUMMARY
          echo '### Inputs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(github.event.inputs) }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  run:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment-name }}
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: ./.github/actions/azure-login
        with:
          github-environment: ${{ github.event.inputs.environment-name }}

      - name: 'Remove pod-identity'
        shell: pwsh
        run: ./tools/infrastructure/remove-aks-app.ps1 -InfA Continue -EnvironmentName ${{ github.event.inputs.environment-name }} -PodIdentityOnly